### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by VinSpee** [Pitzcarraldo/reduxible#2]
The `README` states compatability with IE8, but uglify has `screw_ie8: true` set. It should be clear that the user needs to disable this option to ensure compatibility.

**Comment by pitzcarraldo** [comment]
Thank you so much for your feedback.
Reduxible is working now, but not fully tested.
Compatibility list means that I have wanted to support from IE8.:sweat_smile:
I'll fix webpack config and test in IE8 too.

**Comment by pitzcarraldo** [comment]
It's been a long time.
I've tested and modified Reduxible on the IE8. And it works well now.
(You can test in here > http://reduxible.herokuapp.com)
There were some problems with Redux DevTools. They do not support IE8 and also don't have a schedule for supporting it.
So I've removed dependency with the Redux DevTools. But it can be injected optionally from the Application.

Thanks again :smile:

**Comment by VinSpee** [comment]
Awesome - great work!

On Sat, Jan 23, 2016 at 10:26 AM -0800, "Minkyu Cho" notifications@github.com wrote:

It's been a long time.

I've tested and modified Reduxible on the IE8. And it works well now.

(You can test in here > http://reduxible.herokuapp.com)

There were some problems with Redux DevTools. They do not support IE8 and also don't have a schedule for supporting it.

So I've removed dependency with the Redux DevTools. But it can be injected optionally from the Application.

Thanks again
