### ISSUE TITLE
Have problem with webpack-isomorphic-tools

### ISSUE THREAD

**Issue by arkist** [Pitzcarraldo/reduxible#3]
for the Universal approach (share assets both client&server side), I wanna using [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools).
It use global variable(e.g. `global.webpackIsomorphicTools`) on server-side.

first, declare on entry point.
https://github.com/halt-hammerzeit/webapp/blob/master/code/page-server/entry.js#L12
then using that var on server side render, 
https://github.com/halt-hammerzeit/webapp/blob/master/code/page-server/webpage%20rendering.js#L19
https://github.com/halt-hammerzeit/webapp/blob/master/code/page-server/webpage%20rendering.js#L38

but Reduxible encapsulated it.
https://github.com/Pitzcarraldo/reduxible/blob/master/src/Reduxible.js#L47

so we need a solution for injecting optional var/method on render. lol

**Comment by pitzcarraldo** [comment]
I added 'extras' property to Reduxible default constructor arguments. You can add anythings to Reducible by extras fields, and it will be injected with spreaded.
So if you add something to extras like below,

``` javascript
new Reduxible({
...
    extras: {
      assets : 'something'
    }
  });
```

You can get it in the container like this.

``` javascript
...
    const { component, store, assets } = this.props;
    console.log(asset);//print 'something'
...

```

And webpackIsomorphicTools.refresh() can run in reloader.

This changes deployed version '0.0.2-alpha1'.
You can test with that version, and if you have problem with it, plz comment here.

Here is full example for webpackIsomorphicTools.

``` javascript
export default function reduxible(config) {
  const reloader = (store, combineReducers) => {
    if (config.isDevelopment() && module.hot) {
      module.hot.accept('./reducer/index', () => {
        webpackIsomorphicTools.refresh(); //<<
        const reducer = combineReducers(require('./reducer/index'));
        store.replaceReducer(reducer);
      });
    }
  };

  return new Reduxible({
    config,
    container: Html,
    errorContainer: Error,
    routes,
    middleware,
    reducer,
    reloader,
    extras: {
      assets : webpackIsomorphicTools.assets() //<<
    }
  });
}

```

And this can be another approach.

``` javascript
return new Reduxible({
    config,
    container: Html,
    errorContainer: Error,
    routes,
    middleware,
    reducer,
    reloader,
    extras: {
      assets : () => {
         if(config.isDevelopment()) {
           webpackIsomorphicTools.refresh();
         }
         return webpackIsomorphicTools.assets();
      }
    }
  });
}
```

Thx :)

**Comment by arkist** [comment]
nice :+1: I'll test latest version soon.

**Comment by arkist** [comment]
Still got a problem. 
instance `webpackIsomorphicTools` do not exist on Reduxible's initialize time.
so error occurs:  `webpackIsomorphicTools is not defined`.

**Comment by pitzcarraldo** [comment]
I have tried to apply webpack isomorphic tools to reduxible applicaion.
Here is the sample of it.

https://github.com/Pitzcarraldo/reduxible-example/tree/feature/isomorphic

https://github.com/Pitzcarraldo/reduxible-example/commit/95929dde26e848643c815977efabc46c7155f31b

But this is not finished.
I will make it clear and merge to master branch.
THX

**Comment by pitzcarraldo** [comment]
Webpack Isomorphic Tools is applied to reduxible-example project well.
Ref this project. 
https://github.com/Pitzcarraldo/reduxible-example

THX

Happy New Year!
