### ISSUE TITLE
proposal: use (github|gitlab)-flow

### ISSUE THREAD

**Issue by arkist** [Pitzcarraldo/reduxible#6]
git-flow is verbose. 
(github|gitlab)-flow is good enough IMHO. 
see -> http://doc.gitlab.com/ee/workflow/gitlab_flow.html

we don't need master as a _release_ branch. 
It does not provide any benefits and hides development activities.
just remove `develop` and long live the master :open_hands: (as a _master-develop_)

**Comment by pitzcarraldo** [comment]
Got it, I will remove develop.
I'll use master as develop.
